version: '2'
services:
  jenkins:
    image: florianseidel/capstone-jenkins:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GITHUB_PW