apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: eu-central-1

#TODO: Group for master node!
nodeGroups:
  - name: capstone-green-workers
    labels: { role: green-worker }
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
    availabilityZones: ["eu-central-1a","eu-central-1b"]
    withAddonPolicies:
      ebs: true
      albIngress: true
      autoScaler: true
  - name: capstone-blue-workers
    labels: { role: blue-worker }
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
    availabilityZones: ["eu-central-1a","eu-central-1b"]
    withAddonPolicies:
      ebs: true
      albIngress: true
      autoScaler: true
  - name: capstone-workers
    labels: { role: worker }
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
    availabilityZones: ["eu-central-1a","eu-central-1b"]
    withAddonPolicies:
      ebs: true
      albIngress: true
      autoScaler: true
  - name: capstone-builder
    labels: { role: capstone-builder }
    instanceType: t3.small
    desiredCapacity: 1
    privateNetworking: true
    availabilityZones: ["eu-central-1a"]
    withAddonPolicies:
      imageBuilder: true
      ebs: true
  - name: capstone-support
    labels: { role: capstone-monitoring }
    instanceType: t3.small
    desiredCapacity: 1
    privateNetworking: true
    availabilityZones: ["eu-central-1a"]
    withAddonPolicies:
      ebs: true